image: registry.praxxys.ph:5000/laravel10:latest

include:
    - template: Code-Quality.gitlab-ci.yml

stages:
    - test

unit_test:
    stage: test
    tags:
        - dispatcher
    before_script:
        - service mariadb start
    script:
        - composer install
        - php artisan key:generate --env=testing
        - php artisan storage:link
        - php artisan migrate --seed --env=testing
        - php artisan cms:sync --env=testing
        - php artisan dusk:chrome-driver --detect
        - npm install
        - npm run prod
        - cp .env.testing .env
        - php artisan serve --env=testing &
        - php artisan dusk --env=testing
        - php artisan test

    rules:
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Run code quality job in merge request pipelines
        - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "staging"  || $CI_COMMIT_BRANCH == "live"'
        - if: "$CI_COMMIT_TAG" # Run code quality job in pipelines for tags

code_quality:
    services: # Shut off Docker-in-Docker
    tags:
        - cq-sans-dind # Set this job to only run on our new specialized runner
    rules:
        - if: "$CODE_QUALITY_DISABLED"
          when: never
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Run code quality job in merge request pipelines
        - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH" # Run code quality job in pipelines on the default branch (but not in other branch pipelines)
        - if: "$CI_COMMIT_TAG" # Run code quality job in pipelines for tags

code_quality_html:
    extends: code_quality
    variables:
        REPORT_FORMAT: html
    artifacts:
        paths: [gl-code-quality-report.html]
    rules:
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && ($CI_COMMIT_BRANCH == "staging" || $CI_COMMIT_BRANCH == "live")' # Run code quality HTML job only in `staging` or `live` branches
        - if: "$PRX_ENABLE_CODE_QUALITY_HTML"
