version: '3'
services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        networks:
            - internal
        volumes:
            - '.:/var/www/html'
            - './docker/php/logs/php.log:/var/log/fpm-php.www.log'
        container_name: php
        expose:
            - '9000'
    mysql:
        container_name: db
        restart: unless-stopped
        image: 'mysql:8.3.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - './docker/db-data:/var/lib/mysql'
        networks:
            - internal
networks:
    internal:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
